[SYNC_SETTINGS]
# 数据源 (可选: GARMIN_CN, GARMIN_GLOBAL, COROS)
SOURCE = COROS
# 数据目标 (可选: GARMIN_CN, GARMIN_GLOBAL, COROS)
TARGET = GARMIN_CN
# 同步数据开始时间，如果不填则同步所有数据
SYNC_ACTIVITY_START_TIME = 20250701

[GARMIN_GLOBAL]
# 佳明国际区账号
GARMIN_GLOBAL_EMAIL = cwwcnpds@gmail.com
# 佳明国际区密码
GARMIN_GLOBAL_PASSWORD = Cl2780303!123

[GARMIN_CN]
# 佳明中国区账号
GARMIN_CN_EMAIL = cwwcn@icloud.com
# 佳明中国区密码
GARMIN_CN_PASSWORD = Cl2780303!123

[COROS]
# 高驰账号
COROS_EMAIL = cwwcn@icloud.com
# 高驰密码
COROS_PASSWORD = Cl2780303!123

[RQ_CONFIG]
AESKEY = chenzhuochenweiwen
RQ_EMAIL = cwwcn@icloud.com
RQ_PASSWORD = Cl2780303